services:
  reverse-proxy:
    build:
      context: ./nginx
    ports:
      - "8080:8080"
    depends_on:
      - frontend
      - airflow
    environment:
      - AIRFLOW=airflow
      - FRONTEND=frontend

  frontend:
    build:
      context: ./frontend
    environment:
      # https://node-postgres.com/features/connecting#environment-variables
      - USER=postgres
      - PGHOST=user-db
    depends_on:
      - user-db

  user-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  hadoop:
    build:
      dockerfile: hadoop.Dockerfile
    ports:
      - "8088:8088"
      - "9870:9870"

  airflow:
    build:
      dockerfile: airflow.Dockerfile
    depends_on:
      user-db:
        condition: service_started
      hadoop:
        condition: service_healthy
