FROM marcelmittelstaedt/spark_base:latest
RUN sed -i '44,50 s/^#//' /startup.sh
RUN head -n -9 /startup.sh > temp.sh ; mv temp.sh /startup.sh
RUN echo "echo executing hiveserver2; sudo -u hadoop -H sh -c /home/hadoop/hive/bin/hiveserver2" >> /startup.sh
RUN chmod +x /startup.sh
