services:
  hadoop:
    build:
      dockerfile: Dockerfile.hadoop
    ports:
      - "8088:8088"
      - "9870:9870"
      - "9864:9864"
      - "10000:10000"
      - "8032:8032"
      - "8030:8030"
      - "8031:8031"
      - "9000:9000"
      - "8888:8888"

  airflow:
    build:
      dockerfile: Dockerfile.airflow
    depends_on:
      - hadoop
    ports:
      - "22:22"
      - "8080:8080"
