name: build-airflow
run-name: "Build Airflow container image"
on:
  push:
    paths:
      - airflow.Dockerfile
      - airflow/**
      - spark/**

jobs:
  build-container-image:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        name: "Checkout repository"

      - uses: VaultVulp/gp-docker-action@1.6.0
        name: "Build and upload Docker image"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: airflow
          build-context: ./
          dockerfile: airflow.Dockerfile