name: build-hadoop
run-name: "Build Hadoop container image"
on:
  push:
    paths:
      - hadoop.Dockerfile

jobs:
  build-container-image:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        name: "Checkout repository"

      - uses: VaultVulp/gp-docker-action@1.6.0
        name: "Build and upload Docker image"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: hadoop
          build-context: ./
          dockerfile: hadoop.Dockerfile